import { useState, type FormEvent } from 'react'
import { Bot, Send } from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent, Button, TextArea, Badge } from '@/components/ui'
import { useAuth } from '@/contexts/AuthContext'

export function StudentAIPage() {
  const { user } = useAuth()
  const [question, setQuestion] = useState('')
  const [messages, setMessages] = useState([{ role: 'assistant', content: `Hi ${user?.name?.split(' ')[0] ?? 'there'}! I am Lens, a local placeholder companion. What would you like to learn today?` }])
  const suggestions = ['Explain fractions', 'Help me study for my science quiz', 'What is photosynthesis?', 'Give me a math practice question']
  function sendMessage(event?: FormEvent) { event?.preventDefault(); const trimmed = question.trim(); if (!trimmed) return; setMessages((items) => [...items, { role: 'user', content: trimmed }, { role: 'assistant', content: trimmed.toLowerCase().includes('fraction') ? 'A fraction represents a part of a whole. For example, 1/2 means one out of two equal parts.' : 'Great question! This placeholder companion can help you practice, but it is not connected to saved student data yet.' }]); setQuestion('') }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-text">Lens AI Companion</h1><p className="mt-1 text-sm text-text-muted">A local placeholder scoped to {user?.name ?? 'your student account'}.</p></div><Card><CardHeader className="flex flex-row items-center gap-3"><div className="flex size-10 items-center justify-center rounded-lg bg-secondary-light"><Bot className="size-5 text-secondary" /></div><div><CardTitle>Study chat</CardTitle><Badge variant="secondary" className="mt-1">Local placeholder</Badge></div></CardHeader><CardContent><div className="flex min-h-72 flex-col gap-3 rounded-lg bg-background p-4">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`max-w-[85%] rounded-lg p-3 text-sm ${message.role === 'user' ? 'self-end bg-primary text-white' : 'self-start border border-border bg-surface text-text'}`}>{message.content}</div>)}</div><div className="mt-4 flex flex-wrap gap-2">{suggestions.map((suggestion) => <button key={suggestion} type="button" onClick={() => setQuestion(suggestion)} className="rounded-full border border-border px-3 py-1.5 text-xs text-text-muted hover:border-primary hover:text-primary">{suggestion}</button>)}</div><form onSubmit={sendMessage} className="mt-4 flex items-end gap-3"><TextArea label="Ask Lens" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a learning question..." rows={2} /><Button type="submit" aria-label="Send question"><Send className="size-4" /></Button></form></CardContent></Card></div>
}
