import type { Challenge } from './types'
import { CHALLENGE_BANK_BATCH2 } from './content-batch2'

/** Multi-mode Word Rush bank - expanded to reduce repeats. */
const CHALLENGE_BANK_CORE: Challenge[] = [
  {
    id: 'wc01',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: C _ T',
    answer: 'a',
    options: ['a', 'e', 'i', 'o'],
    explanation: 'CAT is a common pet.',
    word: 'cat',
  },
  {
    id: 'wc02',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: D _ G',
    answer: 'o',
    options: ['a', 'e', 'o', 'u'],
    explanation: 'DOG is a friendly animal.',
    word: 'dog',
  },
  {
    id: 'wc03',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: S U _',
    answer: 'n',
    options: ['n', 'm', 'p', 't'],
    explanation: 'The SUN shines in the day.',
    word: 'sun',
  },
  {
    id: 'wc04',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: B _ OK',
    answer: 'o',
    options: ['o', 'a', 'e', 'i'],
    word: 'book',
  },
  {
    id: 'wc05',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: T R _ E',
    answer: 'e',
    options: ['e', 'a', 'i', 'o'],
    word: 'tree',
  },
  {
    id: 'wc06',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: F L _ W E R',
    answer: 'o',
    options: ['o', 'a', 'e', 'u'],
    word: 'flower',
  },
  {
    id: 'wc07',
    tier: 'explorer',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: H O _ S E',
    answer: 'u',
    options: ['u', 'a', 'e', 'i'],
    word: 'house',
  },
  {
    id: 'wc08',
    tier: 'explorer',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: W A T _ R',
    answer: 'e',
    options: ['e', 'a', 'i', 'o'],
    word: 'water',
  },
  {
    id: 'wc09',
    tier: 'explorer',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Complete the sentence: The bird can ____.',
    answer: 'fly',
    options: ['fly', 'swim', 'drive', 'write'],
    word: 'fly',
  },
  {
    id: 'wc10',
    tier: 'explorer',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Complete the sentence: Fish live in the ____.',
    answer: 'water',
    options: ['water', 'sky', 'tree', 'car'],
    word: 'water',
  },
  {
    id: 'wc11',
    tier: 'challenger',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 3,
    prompt: 'Fill in the missing letter: E L E P _ A N T',
    answer: 'h',
    options: ['h', 't', 'p', 'n'],
    word: 'elephant',
  },
  {
    id: 'wc12',
    tier: 'challenger',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 3,
    prompt: 'Complete: She is reading a ____.',
    answer: 'book',
    options: ['book', 'ball', 'boat', 'bone'],
    word: 'book',
  },
  {
    id: 'sy01',
    tier: 'starter',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means almost the same as HAPPY?',
    answer: 'glad',
    options: ['glad', 'sad', 'angry', 'slow'],
    explanation: 'Glad means happy or pleased.',
    word: 'happy',
  },
  {
    id: 'sy02',
    tier: 'starter',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means almost the same as BIG?',
    answer: 'large',
    options: ['large', 'tiny', 'soft', 'quiet'],
    word: 'big',
  },
  {
    id: 'sy03',
    tier: 'starter',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means almost the same as FAST?',
    answer: 'quick',
    options: ['quick', 'slow', 'heavy', 'dark'],
    word: 'fast',
  },
  {
    id: 'sy04',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as SMART?',
    answer: 'clever',
    options: ['clever', 'noisy', 'empty', 'round'],
    word: 'smart',
  },
  {
    id: 'sy05',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as ANGRY?',
    answer: 'mad',
    options: ['mad', 'calm', 'sleepy', 'funny'],
    word: 'angry',
  },
  {
    id: 'sy06',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as BEGIN?',
    answer: 'start',
    options: ['start', 'finish', 'hide', 'break'],
    word: 'begin',
  },
  {
    id: 'sy07',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as LITTLE?',
    answer: 'small',
    options: ['small', 'huge', 'tall', 'loud'],
    word: 'little',
  },
  {
    id: 'sy08',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as BEAUTIFUL?',
    answer: 'pretty',
    options: ['pretty', 'ugly', 'dirty', 'heavy'],
    word: 'beautiful',
  },
  {
    id: 'sy09',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as SCARED?',
    answer: 'afraid',
    options: ['afraid', 'brave', 'happy', 'tired'],
    word: 'scared',
  },
  {
    id: 'sy10',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as FUNNY?',
    answer: 'hilarious',
    options: ['hilarious', 'serious', 'boring', 'quiet'],
    word: 'funny',
  },
  {
    id: 'an01',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'What is the opposite of HOT?',
    answer: 'cold',
    options: ['cold', 'warm', 'fire', 'sun'],
    word: 'hot',
  },
  {
    id: 'an02',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'What is the opposite of FAST?',
    answer: 'slow',
    options: ['slow', 'quick', 'rapid', 'swift'],
    word: 'fast',
  },
  {
    id: 'an03',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'What is the opposite of DAY?',
    answer: 'night',
    options: ['night', 'morning', 'noon', 'sun'],
    word: 'day',
  },
  {
    id: 'an04',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'What is the opposite of UP?',
    answer: 'down',
    options: ['down', 'high', 'over', 'above'],
    word: 'up',
  },
  {
    id: 'an05',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'What is the opposite of FULL?',
    answer: 'empty',
    options: ['empty', 'heavy', 'open', 'new'],
    word: 'full',
  },
  {
    id: 'an06',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'What is the opposite of LOUD?',
    answer: 'quiet',
    options: ['quiet', 'noisy', 'bright', 'strong'],
    word: 'loud',
  },
  {
    id: 'an07',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'What is the opposite of HAPPY?',
    answer: 'sad',
    options: ['sad', 'glad', 'excited', 'proud'],
    word: 'happy',
  },
  {
    id: 'an08',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'What is the opposite of OPEN?',
    answer: 'closed',
    options: ['closed', 'wide', 'free', 'clear'],
    word: 'open',
  },
  {
    id: 'an09',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'What is the opposite of STRONG?',
    answer: 'weak',
    options: ['weak', 'tough', 'hard', 'firm'],
    word: 'strong',
  },
  {
    id: 'an10',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'What is the opposite of EARLY?',
    answer: 'late',
    options: ['late', 'soon', 'quick', 'first'],
    word: 'early',
  },
  {
    id: 'id01',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "a piece of cake" mean?',
    answer: 'very easy',
    options: ['very easy', 'tastes sweet', 'needs frosting', 'is expensive'],
    explanation: 'If something is a piece of cake, it is easy to do.',
    word: 'piece of cake',
  },
  {
    id: 'id02',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "under the weather" mean?',
    answer: 'feeling sick',
    options: ['feeling sick', 'standing outside', 'loving rain', 'flying a kite'],
    word: 'under the weather',
  },
  {
    id: 'id03',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "hit the books" mean?',
    answer: 'study hard',
    options: ['study hard', 'punch a textbook', 'buy books', 'throw books'],
    word: 'hit the books',
  },
  {
    id: 'id04',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "spill the beans" mean?',
    answer: 'tell a secret',
    options: ['tell a secret', 'drop food', 'cook dinner', 'wash dishes'],
    word: 'spill the beans',
  },
  {
    id: 'id05',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "break the ice" mean?',
    answer: 'start a friendly talk',
    options: ['start a friendly talk', 'smash frozen water', 'feel cold', 'go skating'],
    word: 'break the ice',
  },
  {
    id: 'id06',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "butterflies in my stomach" mean?',
    answer: 'feeling nervous',
    options: ['feeling nervous', 'being hungry', 'eating insects', 'flying away'],
    word: 'butterflies',
  },
  {
    id: 'id07',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "once in a blue moon" mean?',
    answer: 'very rarely',
    options: ['very rarely', 'every night', 'at lunch', 'when it rains'],
    word: 'blue moon',
  },
  {
    id: 'id08',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "cool as a cucumber" mean?',
    answer: 'very calm',
    options: ['very calm', 'very cold', 'green', 'sleepy'],
    word: 'cool as a cucumber',
  },
  {
    id: 'id09',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "let the cat out of the bag" mean?',
    answer: 'reveal a secret',
    options: ['reveal a secret', 'free a pet', 'go shopping', 'clean a room'],
    word: 'cat out of the bag',
  },
  {
    id: 'id10',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "raining cats and dogs" mean?',
    answer: 'raining very hard',
    options: ['raining very hard', 'pets falling', 'sunny day', 'windy'],
    word: 'raining cats and dogs',
  },
  {
    id: 'ps01',
    tier: 'starter',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 1,
    prompt: 'Which word is a NOUN (a person, place, or thing)?',
    answer: 'teacher',
    options: ['teacher', 'run', 'quickly', 'happy'],
    word: 'noun',
  },
  {
    id: 'ps02',
    tier: 'starter',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 1,
    prompt: 'Which word is a VERB (an action word)?',
    answer: 'jump',
    options: ['jump', 'blue', 'desk', 'soft'],
    word: 'verb',
  },
  {
    id: 'ps03',
    tier: 'starter',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 1,
    prompt: 'Which word is an ADJECTIVE (describes a noun)?',
    answer: 'tall',
    options: ['tall', 'run', 'and', 'slowly'],
    word: 'adjective',
  },
  {
    id: 'ps04',
    tier: 'explorer',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 2,
    prompt: 'In the sentence "The dog barked loudly," which word is the VERB?',
    answer: 'barked',
    options: ['barked', 'The', 'dog', 'loudly'],
    word: 'verb',
  },
  {
    id: 'ps05',
    tier: 'explorer',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 2,
    prompt: 'Which word is an ADVERB (often ends in -ly)?',
    answer: 'slowly',
    options: ['slowly', 'slow', 'snail', 'path'],
    word: 'adverb',
  },
  {
    id: 'ps06',
    tier: 'explorer',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 2,
    prompt: 'Which word is a PRONOUN (takes the place of a noun)?',
    answer: 'she',
    options: ['she', 'girl', 'happy', 'run'],
    word: 'pronoun',
  },
  {
    id: 'ps07',
    tier: 'challenger',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 3,
    prompt: 'Which word is a PREPOSITION?',
    answer: 'under',
    options: ['under', 'happy', 'run', 'ball'],
    word: 'preposition',
  },
  {
    id: 'ps08',
    tier: 'challenger',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 3,
    prompt: 'In "She quickly ate the apple," which word is the ADVERB?',
    answer: 'quickly',
    options: ['quickly', 'She', 'ate', 'apple'],
    word: 'adverb',
  },
  {
    id: 'ps09',
    tier: 'explorer',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 2,
    prompt: 'Which word is a NOUN?',
    answer: 'school',
    options: ['school', 'run', 'fast', 'and'],
    word: 'noun',
  },
  {
    id: 'ps10',
    tier: 'starter',
    type: 'part_of_speech',
    modes: ['parts_of_speech', 'mixed'],
    difficulty: 1,
    prompt: 'Which word is a VERB?',
    answer: 'swim',
    options: ['swim', 'water', 'blue', 'fish'],
    word: 'verb',
  },
  {
    id: 'sp01',
    tier: 'starter',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 1,
    prompt: 'How do you spell the word for water from the sky?',
    answer: 'rain',
    options: ['rain', 'rein', 'rane', 'rayn'],
    word: 'rain',
  },
  {
    id: 'sp02',
    tier: 'starter',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 1,
    prompt: 'How do you spell a red fruit that keeps the doctor away?',
    answer: 'apple',
    options: ['apple', 'appel', 'aple', 'aplpe'],
    word: 'apple',
  },
  {
    id: 'sp03',
    tier: 'starter',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 1,
    prompt: 'Which spelling is correct for the animal that meows?',
    answer: 'cat',
    options: ['cat', 'kat', 'catt', 'cet'],
    word: 'cat',
  },
  {
    id: 'sp04',
    tier: 'explorer',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 2,
    prompt: 'Which spelling is correct?',
    answer: 'friend',
    options: ['friend', 'freind', 'frend', 'friand'],
    word: 'friend',
  },
  {
    id: 'sp05',
    tier: 'explorer',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 2,
    prompt: 'Which spelling is correct?',
    answer: 'because',
    options: ['because', 'becuase', 'becouse', 'becaus'],
    word: 'because',
  },
  {
    id: 'sp06',
    tier: 'explorer',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 2,
    prompt: 'Which spelling is correct?',
    answer: 'school',
    options: ['school', 'scool', 'schol', 'skool'],
    word: 'school',
  },
  {
    id: 'sp07',
    tier: 'challenger',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 3,
    prompt: 'Which spelling is correct?',
    answer: 'beautiful',
    options: ['beautiful', 'beatiful', 'beutiful', 'beautifull'],
    word: 'beautiful',
  },
  {
    id: 'sp08',
    tier: 'challenger',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 3,
    prompt: 'Which spelling is correct?',
    answer: 'together',
    options: ['together', 'togather', 'toogether', 'togeter'],
    word: 'together',
  },
  {
    id: 'sp09',
    tier: 'explorer',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 2,
    prompt: 'Which spelling is correct?',
    answer: 'people',
    options: ['people', 'peple', 'peopel', 'peeple'],
    word: 'people',
  },
  {
    id: 'sp10',
    tier: 'starter',
    type: 'spelling',
    modes: ['spelling', 'mixed'],
    difficulty: 1,
    prompt: 'How do you spell the number after two?',
    answer: 'three',
    options: ['three', 'tree', 'thre', 'thrie'],
    word: 'three',
  },
  {
    id: 'sc01',
    tier: 'starter',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 1,
    prompt: 'Unscramble: T A C',
    answer: 'cat',
    options: ['cat', 'act', 'tac', 'cta'],
    word: 'cat',
  },
  {
    id: 'sc02',
    tier: 'starter',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 1,
    prompt: 'Unscramble: N U S',
    answer: 'sun',
    options: ['sun', 'nus', 'usn', 'snu'],
    word: 'sun',
  },
  {
    id: 'sc03',
    tier: 'explorer',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 2,
    prompt: 'Unscramble: L O C S O H',
    answer: 'school',
    options: ['school', 'choose', 'colors', 'closed'],
    word: 'school',
  },
  {
    id: 'sc04',
    tier: 'explorer',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 2,
    prompt: 'Unscramble: R I E F N D',
    answer: 'friend',
    options: ['friend', 'finder', 'refine', 'dinner'],
    word: 'friend',
  },
  {
    id: 'sc05',
    tier: 'explorer',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 2,
    prompt: 'Unscramble: A P L E P',
    answer: 'apple',
    options: ['apple', 'pale', 'plead', 'paper'],
    word: 'apple',
  },
  {
    id: 'sc06',
    tier: 'challenger',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 3,
    prompt: 'Unscramble: R A B I Y R L',
    answer: 'library',
    options: ['library', 'barely', 'briar', 'rarely'],
    word: 'library',
  },
  {
    id: 'sc07',
    tier: 'starter',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 1,
    prompt: 'Unscramble: G O D',
    answer: 'dog',
    options: ['dog', 'god', 'odg', 'gdo'],
    word: 'dog',
  },
  {
    id: 'sc08',
    tier: 'explorer',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 2,
    prompt: 'Unscramble: T E R W A',
    answer: 'water',
    options: ['water', 'rawet', 'tawer', 'wreta'],
    word: 'water',
  },
  {
    id: 'sc09',
    tier: 'challenger',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 3,
    prompt: 'Unscramble: T E A C H E R',
    answer: 'teacher',
    options: ['teacher', 'cheater', 'recheat', 'heaterc'],
    word: 'teacher',
  },
  {
    id: 'sc10',
    tier: 'explorer',
    type: 'word_scramble',
    modes: ['scramble', 'mixed'],
    difficulty: 2,
    prompt: 'Unscramble: H A P P Y',
    answer: 'happy',
    options: ['happy', 'pahpy', 'yppah', 'hppay'],
    word: 'happy',
  },
]

export const CHALLENGE_BANK: Challenge[] = [
  ...CHALLENGE_BANK_CORE,
  ...CHALLENGE_BANK_BATCH2,
]
