import type { Challenge } from './types'

/** Second Word Rush content batch - higher tiers and more depth per mode. */
export const CHALLENGE_BANK_BATCH2: Challenge[] = [
  // --- Expanded bank (batch 2): more depth per mode, higher tiers ---

  {
    id: 'wc13',
    tier: 'explorer',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: P _ N C I L',
    answer: 'e',
    options: ['e', 'a', 'i', 'o'],
    explanation: 'A PENCIL is used for writing.',
    word: 'pencil',
  },
  {
    id: 'wc14',
    tier: 'explorer',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: W I N _ O W',
    answer: 'd',
    options: ['d', 't', 'n', 'k'],
    word: 'window',
  },
  {
    id: 'wc15',
    tier: 'challenger',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 3,
    prompt: 'Fill in the missing letter: B E A _ T I F U L',
    answer: 'u',
    options: ['u', 'a', 'e', 'i'],
    word: 'beautiful',
  },
  {
    id: 'wc16',
    tier: 'challenger',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 3,
    prompt: 'Complete the sentence: She wore a warm coat because it was ____ outside.',
    answer: 'cold',
    options: ['cold', 'loud', 'empty', 'yellow'],
    word: 'cold',
  },
  {
    id: 'wc17',
    tier: 'explorer',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Complete the sentence: Please ____ the door when you leave.',
    answer: 'close',
    options: ['close', 'climb', 'color', 'count'],
    word: 'close',
  },
  {
    id: 'wc18',
    tier: 'starter',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Complete the sentence: Birds can ____ in the sky.',
    answer: 'fly',
    options: ['fly', 'swim', 'dig', 'read'],
    word: 'fly',
  },
  {
    id: 'wc19',
    tier: 'challenger',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 4,
    prompt: 'Fill in the missing letter: K N O W L _ D G E',
    answer: 'e',
    options: ['e', 'a', 'i', 'o'],
    word: 'knowledge',
  },
  {
    id: 'wc20',
    tier: 'advanced',
    type: 'sentence_completion',
    modes: ['word_completion', 'mixed'],
    difficulty: 4,
    prompt: 'Complete the sentence: The scientist used a microscope to ____ the tiny cells.',
    answer: 'observe',
    options: ['observe', 'ignore', 'erase', 'bounce'],
    word: 'observe',
  },
  {
    id: 'wc21',
    tier: 'explorer',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 2,
    prompt: 'Fill in the missing letter: G A R _ E N',
    answer: 'd',
    options: ['d', 't', 'n', 'p'],
    word: 'garden',
  },
  {
    id: 'wc22',
    tier: 'starter',
    type: 'missing_letter',
    modes: ['word_completion', 'mixed'],
    difficulty: 1,
    prompt: 'Fill in the missing letter: F I S _',
    answer: 'h',
    options: ['h', 's', 't', 'k'],
    word: 'fish',
  },
  {
    id: 'sy11',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as HAPPY?',
    answer: 'glad',
    options: ['glad', 'angry', 'heavy', 'silent'],
    word: 'happy',
  },
  {
    id: 'sy12',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as BEGIN?',
    answer: 'start',
    options: ['start', 'finish', 'sleep', 'hide'],
    word: 'begin',
  },
  {
    id: 'sy13',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as ANGRY?',
    answer: 'mad',
    options: ['mad', 'calm', 'sleepy', 'tiny'],
    word: 'angry',
  },
  {
    id: 'sy14',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as QUICK?',
    answer: 'fast',
    options: ['fast', 'slow', 'soft', 'dark'],
    word: 'quick',
  },
  {
    id: 'sy15',
    tier: 'starter',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means almost the same as LITTLE?',
    answer: 'small',
    options: ['small', 'huge', 'loud', 'old'],
    word: 'little',
  },
  {
    id: 'sy16',
    tier: 'advanced',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 4,
    prompt: 'Which word means almost the same as COURAGEOUS?',
    answer: 'brave',
    options: ['brave', 'scared', 'lazy', 'quiet'],
    word: 'courageous',
  },
  {
    id: 'sy17',
    tier: 'explorer',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means almost the same as GIFT?',
    answer: 'present',
    options: ['present', 'problem', 'puzzle', 'pencil'],
    word: 'gift',
  },
  {
    id: 'sy18',
    tier: 'challenger',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means almost the same as ENORMOUS?',
    answer: 'huge',
    options: ['huge', 'tiny', 'narrow', 'gentle'],
    word: 'enormous',
  },
  {
    id: 'sy19',
    tier: 'starter',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means almost the same as LOOK?',
    answer: 'see',
    options: ['see', 'run', 'eat', 'jump'],
    word: 'look',
  },
  {
    id: 'sy20',
    tier: 'advanced',
    type: 'synonym',
    modes: ['synonyms', 'mixed'],
    difficulty: 4,
    prompt: 'Which word means almost the same as DIFFICULT?',
    answer: 'hard',
    options: ['hard', 'easy', 'simple', 'plain'],
    word: 'difficult',
  },
  {
    id: 'an11',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means the opposite of HOT?',
    answer: 'cold',
    options: ['cold', 'warm', 'spicy', 'bright'],
    word: 'hot',
  },
  {
    id: 'an12',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means the opposite of UP?',
    answer: 'down',
    options: ['down', 'high', 'over', 'above'],
    word: 'up',
  },
  {
    id: 'an13',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means the opposite of FULL?',
    answer: 'empty',
    options: ['empty', 'heavy', 'loud', 'round'],
    word: 'full',
  },
  {
    id: 'an14',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means the opposite of DAY?',
    answer: 'night',
    options: ['night', 'sun', 'week', 'hour'],
    word: 'day',
  },
  {
    id: 'an15',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means the opposite of STRONG?',
    answer: 'weak',
    options: ['weak', 'tough', 'solid', 'firm'],
    word: 'strong',
  },
  {
    id: 'an16',
    tier: 'advanced',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 4,
    prompt: 'Which word means the opposite of GENEROUS?',
    answer: 'selfish',
    options: ['selfish', 'kind', 'sharing', 'helpful'],
    word: 'generous',
  },
  {
    id: 'an17',
    tier: 'starter',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 1,
    prompt: 'Which word means the opposite of OPEN?',
    answer: 'closed',
    options: ['closed', 'wide', 'clear', 'free'],
    word: 'open',
  },
  {
    id: 'an18',
    tier: 'explorer',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 2,
    prompt: 'Which word means the opposite of LOUD?',
    answer: 'quiet',
    options: ['quiet', 'noisy', 'busy', 'bright'],
    word: 'loud',
  },
  {
    id: 'an19',
    tier: 'challenger',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 3,
    prompt: 'Which word means the opposite of EARLY?',
    answer: 'late',
    options: ['late', 'soon', 'quick', 'first'],
    word: 'early',
  },
  {
    id: 'an20',
    tier: 'advanced',
    type: 'antonym',
    modes: ['antonyms', 'mixed'],
    difficulty: 4,
    prompt: 'Which word means the opposite of VICTORY?',
    answer: 'defeat',
    options: ['defeat', 'win', 'trophy', 'cheer'],
    word: 'victory',
  },
  {
    id: 'id11',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "piece of cake" mean?',
    answer: 'something easy',
    options: ['something easy', 'a dessert only', 'a hard test', 'a small gift'],
    word: 'piece of cake',
  },
  {
    id: 'id12',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "under the weather" mean?',
    answer: 'feeling sick',
    options: ['feeling sick', 'standing outside', 'loving rain', 'being tall'],
    word: 'under the weather',
  },
  {
    id: 'id13',
    tier: 'starter',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 1,
    prompt: 'What does "hold your horses" mean?',
    answer: 'wait a moment',
    options: ['wait a moment', 'ride a horse', 'run faster', 'buy a pony'],
    word: 'hold your horses',
  },
  {
    id: 'id14',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "hit the books" mean?',
    answer: 'study hard',
    options: ['study hard', 'throw books', 'close a library', 'draw pictures'],
    word: 'hit the books',
  },
  {
    id: 'id15',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "spill the beans" mean?',
    answer: 'tell a secret',
    options: ['tell a secret', 'cook dinner', 'drop food', 'plant seeds'],
    word: 'spill the beans',
  },
  {
    id: 'id16',
    tier: 'advanced',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 4,
    prompt: 'What does "the ball is in your court" mean?',
    answer: 'it is your turn to act',
    options: ['it is your turn to act', 'you play basketball', 'the game is over', 'you lost the ball'],
    word: 'ball is in your court',
  },
  {
    id: 'id17',
    tier: 'starter',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 1,
    prompt: 'What does "zip your lip" mean?',
    answer: 'be quiet',
    options: ['be quiet', 'fix a coat', 'run away', 'smile big'],
    word: 'zip your lip',
  },
  {
    id: 'id18',
    tier: 'explorer',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 2,
    prompt: 'What does "butterflies in my stomach" mean?',
    answer: 'feeling nervous',
    options: ['feeling nervous', 'being hungry', 'liking insects', 'flying away'],
    word: 'butterflies in my stomach',
  },
  {
    id: 'id19',
    tier: 'challenger',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 3,
    prompt: 'What does "once in a blue moon" mean?',
    answer: 'very rarely',
    options: ['very rarely', 'every night', 'at lunch', 'in winter only'],
    word: 'once in a blue moon',
  },
  {
    id: 'id20',
    tier: 'advanced',
    type: 'idiom',
    modes: ['idioms', 'mixed'],
    difficulty: 4,
    prompt: 'What does "bite off more than you can chew" mean?',
    answer: 'take on too much',
    options: ['take on too much', 'eat quickly', 'skip dinner', 'share food'],
    word: 'bite off more than you can chew',
  }
]
