import type { Challenge } from './types'

/** Structured seed bank. UI must not hard-code challenges. Expand later. */
export const CHALLENGE_BANK: Challenge[] = [
  {
    id: 's1',
    tier: 'starter',
    type: 'missing_letter',
    difficulty: 1,
    prompt: 'Fill in the missing letter: C _ T',
    answer: 'a',
    options: ['a', 'e', 'i', 'o'],
    explanation: 'CAT is a common pet.',
    word: 'cat',
  },
  {
    id: 's2',
    tier: 'starter',
    type: 'missing_letter',
    difficulty: 1,
    prompt: 'Fill in the missing letter: D _ G',
    answer: 'o',
    options: ['a', 'e', 'o', 'u'],
    explanation: 'DOG is a friendly animal.',
    word: 'dog',
  },
  {
    id: 's3',
    tier: 'starter',
    type: 'word_builder',
    difficulty: 1,
    prompt: 'Which letters make the word for a big yellow fruit?',
    answer: 'banana',
    options: ['banana', 'orange', 'grape', 'lemon'],
    word: 'banana',
  },
  {
    id: 's4',
    tier: 'starter',
    type: 'spelling',
    difficulty: 2,
    prompt: 'How do you spell the word for water from the sky?',
    answer: 'rain',
    options: ['rain', 'rein', 'rane', 'rayn'],
    word: 'rain',
  },
  {
    id: 's5',
    tier: 'starter',
    type: 'missing_letter',
    difficulty: 1,
    prompt: 'Fill in the missing letter: S U _',
    answer: 'n',
    options: ['n', 'm', 'p', 't'],
    explanation: 'SUN shines in the day.',
    word: 'sun',
  },
  {
    id: 's6',
    tier: 'starter',
    type: 'spelling',
    difficulty: 1,
    prompt: 'How do you spell a red fruit that keeps the doctor away?',
    answer: 'apple',
    options: ['apple', 'appel', 'aple', 'aplpe'],
    word: 'apple',
  },
  {
    id: 's7',
    tier: 'starter',
    type: 'word_builder',
    difficulty: 1,
    prompt: 'Which word is a place where you learn?',
    answer: 'school',
    options: ['school', 'sleep', 'shoe', 'ship'],
    word: 'school',
  },
  {
    id: 'e1',
    tier: 'explorer',
    type: 'synonym',
    difficulty: 2,
    prompt: 'Which word means almost the same as HAPPY?',
    answer: 'glad',
    options: ['glad', 'sad', 'angry', 'slow'],
    explanation: 'Glad means happy or pleased.',
    word: 'happy',
  },
  {
    id: 'e2',
    tier: 'explorer',
    type: 'antonym',
    difficulty: 2,
    prompt: 'What is the opposite of HOT?',
    answer: 'cold',
    options: ['cold', 'warm', 'fire', 'sun'],
    word: 'hot',
  },
  {
    id: 'e3',
    tier: 'explorer',
    type: 'word_scramble',
    difficulty: 3,
    prompt: 'Unscramble: L O C S O H',
    answer: 'school',
    options: ['school', 'choose', 'colors', 'closed'],
    word: 'school',
  },
  {
    id: 'e4',
    tier: 'explorer',
    type: 'synonym',
    difficulty: 2,
    prompt: 'Which word means almost the same as BIG?',
    answer: 'large',
    options: ['large', 'tiny', 'soft', 'quiet'],
    word: 'big',
  },
  {
    id: 'e5',
    tier: 'explorer',
    type: 'antonym',
    difficulty: 2,
    prompt: 'What is the opposite of FAST?',
    answer: 'slow',
    options: ['slow', 'quick', 'rapid', 'swift'],
    word: 'fast',
  },
  {
    id: 'c1',
    tier: 'challenger',
    type: 'definition',
    difficulty: 3,
    prompt: 'A place where books are kept and borrowed is a library.',
    answer: 'library',
    options: ['library', 'kitchen', 'garage', 'garden'],
    word: 'library',
  },
  {
    id: 'c2',
    tier: 'challenger',
    type: 'context',
    difficulty: 4,
    prompt: 'The sky was clear and the sun was bright. The weather was?',
    answer: 'sunny',
    options: ['sunny', 'rainy', 'foggy', 'stormy'],
    word: 'sunny',
  },
  {
    id: 'c3',
    tier: 'challenger',
    type: 'sentence_completion',
    difficulty: 3,
    prompt: 'She used a _____ to write in her notebook.',
    answer: 'pencil',
    options: ['pencil', 'plate', 'pillow', 'plant'],
    word: 'pencil',
  },
  {
    id: 'a1',
    tier: 'advanced',
    type: 'synonym',
    difficulty: 4,
    prompt: 'Which word is closest in meaning to BRAVE?',
    answer: 'courageous',
    options: ['courageous', 'careful', 'quiet', 'tiny'],
    word: 'brave',
  },
  {
    id: 'm1',
    tier: 'master',
    type: 'definition',
    difficulty: 5,
    prompt: 'Something that is very unusual or rare can be called?',
    answer: 'extraordinary',
    options: ['extraordinary', 'ordinary', 'average', 'simple'],
    word: 'extraordinary',
  },
]
